services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brightside\Addresses\DataProcessing\AddressesDatabaseQueryProcessor:
    public: true

  Brightside\Addresses\ViewHelpers\ImageViewHelper:
    public: true
